spring.application.name=memora-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/memora
spring.datasource.username=postgres
spring.datasource.password=admin
spring.cloud.gcp.sql.enabled=false

cloud.bucketName=memora-1

spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
server.tomcat.max-part-count=200

security.jwt.secret-key=vJfmeSsdgewEWC6PPoWwYrACN5PlcEtvzaqCXT66LAXUdabDtrFnkTsXtyW4IWnGm070dgWpcOw9JB5z8AVrBj
security.jwt.expiration-time=3600000

app.cors.allowed-origins=http://localhost:4200