spring.application.name=memora-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/memora
spring.datasource.username=postgres
spring.datasource.password=admin

cloud.bucketName=memora-1

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

base-url=http://localhost:8080

security.jwt.secret-key=cbfb9d103cd7439df93f5bf4e597a26b5951d2d43ef94d41831fdfd4bf623305
security.jwt.expiration-time=3600000