spring.application.name=memora-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

cloud.bucketName=${BUCKET_NAME}

spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
server.tomcat.max-part-count=200

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=3600000