spring.application.name=memora-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

cloud.bucketName=${BUCKET_NAME}

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=3600000