CREATE TABLE multimedia
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_file_name   VARCHAR(255)                            NOT NULL,
    content_type         VARCHAR(255)                            NOT NULL,
    size                 BIGINT                                  NOT NULL,
    bucket_name          VARCHAR(255)                            NOT NULL,
    object_key           VARCHAR(255)                            NOT NULL,
    thumbnail_object_key VARCHAR(255)                            NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    upload_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    CONSTRAINT pk_multimedia PRIMARY KEY (id)
);

ALTER TABLE multimedia
    ADD CONSTRAINT FK_MULTIMEDIA_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);