CREATE TABLE multimedia
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url         VARCHAR(255)                            NOT NULL,
    type        SMALLINT                                NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_multimedia PRIMARY KEY (id)
);